spring.application.name=gascalendar
spring.datasource.url=jdbc:postgresql://localhost:5432/gasDB
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver